import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { getMonth } from "../utils/getMonth";

const Home: NextPage = () => {
  console.table(getMonth(new Date().getMonth()));

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Calender</h1>
      </main>
    </div>
  );
};

export default Home;
